### ISSUE TITLE
Option to switch off display of culprits

### ISSUE THREAD

**Issue by ralfwelt** [jan-molak/jenkins-build-monitor-plugin#243] opened 2016-07-05 07:27 UTC
We are using the Build monitor plugin with great success. However, the team members don't like the display of culprits.
IIRC, in the first version I installed there was an option to switch off culprits display.
Unfortunately I cannot find it in the current version.
Do I miss something?
If not, can you point me to the version before this option was removed?

**Comment by jan-molak** [comment] 2016-07-05 23:18
Hey @ralfwelt, that's great to hear! I'm contemplating making this and other options a bit more configurable, so I'll add your request to the backlog.

Having said that, does your team use the [Claim Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Claim+plugin)? 

Claiming a broken build greatly improves the visibility of who's working on fixing the problem and tells everyone looking at your Build Monitor that your builds are not ignored by the team and left broken. When a build is claimed, the culprits are no longer displayed either.

It's pretty easy to set up, have a look at the [acceptance tests](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/index.html) and the "Claiming a broken build" scenario in particular for step-by-step instructions.

**Comment by ralfwelt** [comment] 2016-07-06 05:12
Hi Jan,

thanks for your quick reply and adding my request to the backlog.

At least in Germany a lot of engineers will object to displaying the culprits, so please don’t set the priority too low ☺

Also thanks for mentioning the Claim Plugin, I will check it out.



Regards,
Ralf

**Comment by cialx** [comment] 2016-07-28 08:39
In our department (medium-sized German company) we are using Build Monitor Plugin for a public status monitor, but we (and the workers' counci) don't want to have the names of possible culprits displayed there, not even for the time until someone claimed the broken build.
Without this possibility we cannot use this plugin anymore. It would be great if you wold reconsider adding a local (or, even better for us: global) mechanism for disabling to show culprits.

**Comment by jan-molak** [comment] 2016-07-28 18:27
Thanks for the explanation, @cialx. The point of showing the identifiers of people who might have caused the build to break as well as those who have committed their changes on a broken build was not to publicly blame anyone 😞 

It's supposed to serve informational purposes only. This way the rest of the team (or other teams at larger organisations) know who to ask about the problem and offer their help with fixing the build. It's pretty useful when you have 500 people working across several countries and committing their code to one repository. 

Like I mentioned in #70, claiming a broken build helps to improve transparency and quickly tell all the interested people that someone is working on fixing the problem.

---

Having said that, I wonder if it's a problem with vocabulary perhaps?

Maybe saying "possible culprits" is too _offensive_? What do you think?

Just thinking aloud here, would saying "The build has failed, John and Ben could know something about it" be better than "The build has failed. Possible culprits: John and Ben".

The word "culprit" might imply that in our example John and Ben are to blame, so maybe we should rephrase that?

One way or another I'm happy with adding an option to disable the "display of culprits" altogether. 
However, I'd like to make the message friendly for the teams that find value in it, so your thoughts are appreciated!

Best,
Jan

**Comment by cialx** [comment] 2016-07-29 07:09
I found out that the problem is not that people are adressed as culprits, but that it's possible to see publicly which person is working on which project. That is a problem since we have a lot of external personnel. In Germany, external workers are not allowed to be involved in internal company matters unrelated to there own work, sometimes they are not even allowed to sit in the same office as the internal staff.

You're right, it doesn't say culprites anymore (we're using Build Monitor version 1.9+build.201606131328), but that doesn't help us ;)
"The build has failed after John and Ben committed their changes" seems perfect to me. Personally, I like this feature very much, but my hands are bound.

Greetings, cialx

**Comment by ChadiEM** [comment] 2016-07-30 19:11
A suggestion/workaround would be to create mirror jobs of your actual jobs that get triggered automatically and have their status the same as their triggering job via a Groovy postbuild script for example. The mirror jobs in this case will not have any committers in it. What do you think?

**Comment by jan-molak** [comment] 2016-07-30 19:25
@ChadiEM that's a good point, although @cialx's argumentation has convinced me.

I'm planning to make the `headline` a bit more configurable. This requires some changes to the Build Monitor domain model, but they should make adding new features, like #250, so much easier.

I'm aiming for a release within the next couple of days so stay tuned 😄

**Comment by cialx** [comment] 2016-08-01 06:20
@ChadiEM It would get a little bit harder to manage all our jobs, but seems like a good workaround, thanks!

@jan-molak Nice, lookin forward to it! Thank you very much for your efforts!!

**Closed** 2016-08-01 13:46 UTC
