### ISSUE TITLE
Support multiproject/multibranch pipeline in build monitor

### ISSUE THREAD

**Issue by ottlinger** [jan-molak/jenkins-build-monitor-plugin#385] opened 2018-07-13 13:12 UTC
At the moment only non-multibranch pipeline projects are visible in the monitor.

If I add a multibranch pipeline to the monitor the project is not shown at all.

Running on
`Build Monitor version 1.12+build.201805070054 with `

**Comment by Crayon2000** [comment] 2018-07-13 23:00
This is a duplicate of https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/246

Check last comment by gothrek22, this may help you.

**Comment by jan-molak** [comment] 2018-09-06 19:05
Let's track this under #246

**Closed by jan-molak** 2018-09-06 19:05 UTC
