### ISSUE TITLE
Jenkins ran into a problem

### ISSUE THREAD

**Issue by naggie** [jan-molak/jenkins-build-monitor-plugin#290] opened 2017-02-03 09:21 UTC
First of all, thanks for the incredibly useful dashboard.

It seems that we get the "Jenkins ran into a problem" about twice a day sometimes. I don't know why this happens, but I feel it would be a useful feature for the dashboard to re-attempt a minute or so later, else it's necessary to manually refresh all screens.

Thanks
Cal

**Comment by jan-molak** [comment] 2017-02-03 15:19
Hey @naggie and thanks for the kind words :-)

Did you perhaps notice if there are any errors mentioned in the JavaScript console of your browser?
Or the Jenkins log perhaps?

Sometimes this problem might happen when Jenkins is behind a proxy, which caches the auth token.

J

**Comment by naggie** [comment] 2017-02-03 15:38
Hi Jan,

Next time it happens I'll try to look at the logs, I think it's long gone now. It's running on a Pi QTwebkit, I can try to get a console. I'll try to get a picture.

Thanks

**Comment by jan-molak** [comment] 2017-02-03 15:39
That would be very helpful, thanks! :-) I'll leave this ticket open so that you can update it with more details, or close it if the problem is gone.

**Comment by jan-molak** [comment] 2017-02-25 21:42
Closing the issue as it doesn't seem related to Build Monitor. @naggie please feel free to re-open it should the problem occur again.

Best,
Jan

**Closed by jan-molak** 2017-02-25 21:42 UTC

**Comment by naggie** [comment] 2017-02-26 10:00
I know it's not related to build monitor, it's just that the situation is temporary situation recoverable by build monitor -- a refresh could happen after 30 seconds or something. Anyway, I think it's only happened once since and I wasn't there, so no longer an issue that affects me.
Thanks all the same!

**Comment by jan-molak** [comment] 2017-02-26 13:16
No worries, let me know should you need help!

I considered refreshing automatically upon a Jenkins failure, but the trouble is that Jenkins marks different errors with the same 404, so it's very hard to figure out what's actually give wrong and whether an automatic refresh will really help. Sometimes we still need humans to make the call ;-)
