### ISSUE TITLE
Compatability with Cloudbees folder plugin

### ISSUE THREAD

**Issue by morgan-graybill** [jan-molak/jenkins-build-monitor-plugin#155] opened 2015-06-17 18:27 UTC
Hi there,
We use your build monitor plugin and love it, but we're having issues with downstream compatibility with the folders plugin.
What we would like to do is create a folder which contains a bunch of build monitors, so that they do not clutter our project's top level view. However, once we are in the folder and go to create a build monitor, we do not see any of our jobs and cannot write a regex to get them, either.

Thanks,
Morgan

**Comment by jan-molak** [comment] 2015-06-29 16:38
Hi Morgan and thanks for your kind words! I'm glad that you find this little plugin useful :smile:

The functionality you're thinking of is not (yet) available. 
I'll be looking into making Build Monitor support Cloudbees Folder more fully as part of #130, and there's a good chance that I'll be able to work on your requirement as well (of course pull requests are also very welcome!).

In the meantime though you might want to give the [Team Views Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Team+Views+Plugin) a try. It allows you to define team areas in Jenkins and give each team its Build Monitor(s). Alternatively you could create a "Build Monitors" team and put your different Build Monitor views in there, which then prevents the proliferation of tabs on the main Jenkins page.

Hope this helps!

**Comment by jan-molak** [comment] 2015-08-30 14:50
Closing as duplicate of #130

**Closed by jan-molak** 2015-08-30 14:50 UTC
