### ISSUE TITLE
Sorry to bother you, but there is a slight issue ...

### ISSUE THREAD

**Issue by dannickmontanede** [jan-molak/jenkins-build-monitor-plugin#245] opened 2016-07-07 10:28 UTC
Hello, i run jenkins in container engine and i have the 'No valid crumb' everytime so i tried Build Monitor to fix my issue but no result.

Please help 

<img width="1280" alt="capture d ecran 2016-07-07 a 12 22 50" src="https://cloud.githubusercontent.com/assets/16313587/16650337/ea44508a-443d-11e6-91c0-ea58be7e3a7e.png">

**Comment by jan-molak** [comment] 2016-07-07 14:01
Hey @dannickmontanede what version of Jenkins are you on? Some time ago Jenkins changed how it deals with the .crumb header and that might confuse servers such as Nginx if you happen to be using one? See #215

**Comment by dannickmontanede** [comment] 2016-07-07 14:57
i use 2.12 version, i've ever seen #215  and try your last build but the problem stay the same and i don't what is this 403 error

**Comment by jan-molak** [comment] 2016-07-07 15:25
Is there any caching or load balancing happening between your Jenkins and the browser? If that's the case then the problem might be related to issues #166 and #231, fixed in [this build](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/47/artifact/build-monitor-plugin/target/build-monitor-plugin.hpi). Perhaps you'd like to give that build a try?

**Comment by dannickmontanede** [comment] 2016-07-07 15:44
yes you right i used a load balancer, but i added
<img width="799" alt="capture d ecran 2016-07-07 a 17 41 45" src="https://cloud.githubusercontent.com/assets/16313587/16659436/4cfd6316-446a-11e6-966d-3d2aff45c89b.png">
<img width="1280" alt="capture d ecran 2016-07-07 a 17 42 24" src="https://cloud.githubusercontent.com/assets/16313587/16659444/54e515ce-446a-11e6-8c7d-e1d0b3ec676a.png">
<img width="1280" alt="capture d ecran 2016-07-07 a 17 42 32" src="https://cloud.githubusercontent.com/assets/16313587/16659448/59c82630-446a-11e6-9726-6a9269decd12.png">


 your build and the problem is the same

**Comment by dannickmontanede** [comment] 2016-07-07 15:45
i added your build and i've the 403 error for each reload

**Comment by jan-molak** [comment] 2016-07-07 16:18
Interesting... This doesn't seem like a problem with Build Monitor, but most likely with some component between Jenkins and the Build Monitor dashboard.

Perhaps this helps you with investigating what's going on:
- whenever a user loads the Build Monitor dashboard for the first time, Jenkins generates a unique token for them, called the `.crumb` (it might be called `Jenkins-Crumb` on [Jenkins 2.x](https://github.com/jenkinsci/jenkins/compare/4649e04cbe58...a87c38c5052c)). This token is unique for every user and you can see its value within the page source of the dashboard:
<img width="981" alt="screen shot 2016-07-07 at 17 04 13" src="https://cloud.githubusercontent.com/assets/1089173/16660103/ec91184c-4464-11e6-86e5-caed34b3d10d.png">
- this header (`1e5e00e5-ba09-4bcf-87d4-3c2eba2a729c` in this case) is attached to every requests Build Monitor makes to Jenkins and that's how Jenkins verifies where a given request came from:
<img width="812" alt="screen shot 2016-07-07 at 17 05 44" src="https://cloud.githubusercontent.com/assets/1089173/16660182/3cdbe192-4465-11e6-918f-a60d83e61ab0.png">

The things that can go wrong:
- If there's a caching layer between the Jenkins server and the browser displaying the Build Monitor dashboard, it might cache the HTML and the original value of the `.crumb` token, causing multiple users to use the same `.crumb` and Jenkins to return a 403.
- There was a problem with Nginx and Jenkins 2.x some time ago, where Nginx (acting as a proxy) removed the `.crumb` header (if I remember correctly that was because it starts with a `.`), that's why recent versions of Jenkins use the `Jenkins-Crumb` instead. If you have Nginx in your setup and your Jenkins is configured to use `.crumb` rather than `Jenkins-Crumb`, it might be that Nginx removes the header and Jenkins has no way of verifying the request.

Hope this helps!
J

**Comment by jan-molak** [comment] 2016-07-28 18:09
Closing as @dannickmontanede and I found out that the problem is not related to Build Monitor but to the Nginx configuration.

**Closed by jan-molak** 2016-07-28 18:09 UTC
