### ISSUE TITLE
Build monitor plugin slow to open config page with lots of jobs

### ISSUE THREAD

**Issue by jonathanbrecher** [jan-molak/jenkins-build-monitor-plugin#74] opened 2014-07-25 15:57 UTC
We have a Jenkins server with ~1,100 jobs. It takes over 50 seconds just to open the config page for any Build Monitor Plugin view. That's far too slow.

Responding to question raised in [JENKINS-23352](https://issues.jenkins-ci.org/browse/JENKINS-23352) (Also, have you considered using the Cloudbees folder plugin to group those ~1,100 jobs?): We're using the Nested View plugin. We reviewed both plugins. Comments from our users included:
* The Nested View plugin feels a little more intuitive than the folder one.
* CloudBees folder Plugin ->  Create a new “Job” folder type, to hold jobs, feels kinda hacky. Nested Views -> Create a view, contains other views
* I took a look at both plugins, and it looks like the nested view plugin looks way more feature rich and intuitive to the user.  
* The Nested View plugin is definitely the winner here, it doesn’t require you to recreate jobs and seems a lot less hacky/funky to work.

**Comment by jan-molak** [comment] 2015-04-25 20:16
@jonathanbrecher - are you still observing the issue you described in the ticket?

**Comment by jonathanbrecher** [comment] 2015-04-27 15:03
I've moved to a different team since this ticket was opened. I checked with the folks currently in charge of our Jenkins instance(s), and they blacklisted this plugin a while ago. They were unable to uninstall it cleanly, so they blocked all traffic to it via apache/nginx rules upstream. Given that pain, they are not interested in reactivating it to check the current status. Sorry!

**Comment by jan-molak** [comment] 2015-04-27 15:25
Sorry to hear that, it sounds a bit dramatic! Hope that the issue is fixed in future versions of the Role Strategy plugin and it scales better :-(
I'll close the ticket as it doesn't seem related to Build Monitor.

**Closed by jan-molak** 2015-04-27 15:25 UTC

**Comment by ripplegupta03** [comment] 2017-02-22 09:25
@jan-molak Firstly want to thanks for this awesome plugin.
 We are using monitor view to show status of our builds and our builds are running automation on our products.
Each job in view is displaying an information which i do not want, that "last number of build failed." (See screenshot attached) Unstable builds are also taken into consideration but i dnt want to confuse audience as unstable build is good for me than failed build.
Can i remove that piece of information somehow. In documentation i dont see this information displayed on failed builds but dnt know why its been shown on my view.

Thanks a lot in advance.
![capture](https://cloud.githubusercontent.com/assets/10498112/23205171/e6ae5c5a-f90e-11e6-9829-caaf794655ea.JPG)
